In [9]:
import pandas as pd

# Paths to your files
file_a_path = 'noecall.xlsx' # File with all chemicals'  # Replace with the file path
file_b_path = 'noecafterknime.xlsx'   # File Path of Curated Chemical  # Replace with the file path

In [10]:
# Load the data into DataFrames
df_a = pd.read_excel (file_a_path)
df_b = pd.read_excel (file_b_path)
df_a

,CAS Number,Chemical Name,Species Scientific Name,Species Group,Conc Mean,Conc Units
0,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.500,AI mg/L
1,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.500,AI mg/L
2,50022,"11beta,16alpha-9-Fluoro-11,17,21-Trihydroxy-16...",Ambystoma mexicanum,Amphibians,50.000,ug
3,50022,"11beta,16alpha-9-Fluoro-11,17,21-Trihydroxy-16...",Ambystoma mexicanum,Amphibians,100.000,ug
4,50022,"11beta,16alpha-9-Fluoro-11,17,21-Trihydroxy-16...",Ambystoma mexicanum,Amphibians,50.000,ug
...,...,...,...,...,...,...
140332,52315078,Cypermethrin,Chironomus tentans,Insects/Spiders,0.025,mg/kg
140333,52315078,Cypermethrin,Chironomus tentans,Insects/Spiders,0.014,mg/kg
140334,149961524,Dimoxystrobin,Chironomus riparius,Insects/Spiders,10.000,µg/l
140335,7440666,Zinc,Hyalella azteca,Crustaceans,488.000,mg/kg
140336,5466773,2-Ethylexyl 4-methoxycinnamate,Melanoides tuberculata,Molluscs,2.000,mg/kg

In [11]:
# Ensure that both DataFrames have a column named 'Chemical Name'
chemical_name_column = 'Chemical Name'
# Filter df_a to only include rows where the chemical_name exists in df_b
filtered_df_a = df_a[df_a[chemical_name_column].isin(df_b[chemical_name_column])]

In [12]:
# Save the filtered DataFrame to a new file
filtered_file_a_path = "NOECremovedthechemicalwasnotcurated.csv"
filtered_df_a.to_csv(filtered_file_a_path, index=False)

In [13]:
filtered_df_a

,CAS Number,Chemical Name,Species Scientific Name,Species Group,Conc Mean,Conc Units
0,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.5,AI mg/L
1,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.5,AI mg/L
56,50066,"5-Ethyl-5-phenyl-2,4,6(1H,3H,5H)-pyrimidinetrione",Pleurodeles waltl,Amphibians,100.0,AI mg/L
57,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Rhinella arenarum,Amphibians,40.0,AI mg/L
58,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Hypsiboas pulchellus,Amphibians,40.0,AI mg/L
...,...,...,...,...,...,...
140056,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.0,µg/l
140066,83329,Acenaphthene,Pimephales promelas,Fish,332.0,µg/l
140067,83329,Acenaphthene,Pimephales promelas,Fish,345.0,µg/l
140068,83329,Acenaphthene,Pimephales promelas,Fish,509.0,µg/l
140179,114078,Erythromycin,Anabaena flos-aquae,Cyanophyceae,30.0,µg/l

In [18]:
species_to_remove = ['Fish', 'Flowers, Trees, Shrubs, Ferns', 'Fungi', 'Echinodermata', 'Mammals', 'Mussels', 'Microorganisms', 'Rotifers', 'Birds', 'Moss, Hornworts', 'Cyanophyceae']

# Filter the DataFrame to remove specified species
df_filtered2 = filtered_df_a[~filtered_df_a['Species Group'].isin(species_to_remove)]
df_filtered2

,CAS Number,Chemical Name,Species Scientific Name,Species Group,Conc Mean,Conc Units
0,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.50,AI mg/L
1,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.50,AI mg/L
56,50066,"5-Ethyl-5-phenyl-2,4,6(1H,3H,5H)-pyrimidinetrione",Pleurodeles waltl,Amphibians,100.00,AI mg/L
57,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Rhinella arenarum,Amphibians,40.00,AI mg/L
58,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Hypsiboas pulchellus,Amphibians,40.00,AI mg/L
...,...,...,...,...,...,...
140044,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l
140045,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l
140046,104405,4-Nonylphenol,Daphnia magna,Crustaceans,0.12,µg/l
140047,104405,4-Nonylphenol,Daphnia magna,Crustaceans,0.04,µg/l
140056,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l

In [19]:
# Define the species to replace
species_to_replace = ['Insects/Spiders', 'Molluscs', 'Worms', 'Reptiles']
new_df = df_filtered2.copy()
new_df['Species Group'] = new_df['Species Group'].replace(species_to_replace, 'Other Invertebrates')
new_df

,CAS Number,Chemical Name,Species Scientific Name,Species Group,Conc Mean,Conc Units
0,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.50,AI mg/L
1,50000,Formaldehyde,Lithobates catesbeianus,Amphibians,0.50,AI mg/L
56,50066,"5-Ethyl-5-phenyl-2,4,6(1H,3H,5H)-pyrimidinetrione",Pleurodeles waltl,Amphibians,100.00,AI mg/L
57,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Rhinella arenarum,Amphibians,40.00,AI mg/L
58,50180,"N,N-Bis(2-chloroethyl)tetrahydro-2H-1,3,2-oxaz...",Hypsiboas pulchellus,Amphibians,40.00,AI mg/L
...,...,...,...,...,...,...
140044,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l
140045,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l
140046,104405,4-Nonylphenol,Daphnia magna,Crustaceans,0.12,µg/l
140047,104405,4-Nonylphenol,Daphnia magna,Crustaceans,0.04,µg/l
140056,104405,4-Nonylphenol,Desmodesmus subspicatus,Algae,450.00,µg/l

In [21]:
new_df.to_csv('NOECremovedunspeciesandmergedspecies.csv', index=False)